services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    # arm環境で動かない場合以下のオプションを試す
    # platform: linux/arm64/v8
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    # コンテナ内部にのみ公開
    expose:
      - "5432"

  api:
    container_name: api
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    # ローカルの./backend配下をコンテナの/codeにマウントする
    # 本番環境ではstaticもマウントする
    volumes:
      - ./backend:/api
    ports:
      - "8500:8500"
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    # コンテナ:dbが立ち上がってからdjangoを起動する
    depends_on:
      db:
        condition: service_healthy

  receipt:
    container_name: receipt
    build:
      context: .
      dockerfile: containers/receiptline/Dockerfile
    # コンテナ内部にのみ公開
    expose:
      - "6573"

volumes:
  db_data: